{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e50a9bf3-7f3c-40b0-a9fc-d4fe8745cae4",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List, Dict\n",
    "import openai\n",
    "from dotenv import load_dotenv\n",
    "import os\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "class TableLocator:\n",
    "    def __init__(self):\n",
    "        self.openai_client = openai.OpenAI(api_key=os.getenv(\"OPENAI_API_KEY\"))\n",
    "        self.table_metadata = {}  # 存储表的元数据信息\n",
    "        \n",
    "    def load_table_metadata(self, table_metadata: Dict[str, Dict]):\n",
    "        \"\"\"加载表的元数据信息\"\"\"\n",
    "        self.table_metadata = table_metadata\n",
    "        \n",
    "    def _get_table_partition_info(self, table_name: str) -> Dict:\n",
    "        \"\"\"\n",
    "        获取表的分区信息\n",
    "        :param table_name: 表名\n",
    "        :return: 分区信息\n",
    "        \"\"\"\n",
    "        if table_name not in self.table_metadata:\n",
    "            raise ValueError(f\"未找到表 {table_name} 的元数据信息\")\n",
    "            \n",
    "        table_info = self.table_metadata[table_name]\n",
    "        return {\n",
    "            \"table_name\": table_name,\n",
    "            \"project_name\": table_info[\"project_name\"],\n",
    "            \"table_type\": table_info[\"table_type\"],\n",
    "            \"is_partitioned\":table_info[\"is_partitioned\"],\n",
    "            \"partition_column\": table_info[\"partition_column\"],\n",
    "            \"partition_type\": table_info[\"partition_type\"],\n",
    "            \"columns\": table_info[\"columns\"]\n",
    "        }\n",
    "        \n",
    "    def locate_tables(self, question: str) -> List[Dict]:\n",
    "        \"\"\"\n",
    "        根据用户问题定位相关表\n",
    "        :param question: 用户问题\n",
    "        :return: 相关表信息列表\n",
    "        \"\"\"\n",
    "        # 构建提示信息\n",
    "        table_info = []\n",
    "        for table_name, info in self.table_metadata.items():\n",
    "            project_name = info[\"project_name\"]\n",
    "            table_type = info[\"table_type\"]\n",
    "            partition_info = {\n",
    "                \"is_partitioned\": info[\"is_partitioned\"],\n",
    "                \"partition_column\": info[\"partition_column\"],\n",
    "                \"partition_type\": info[\"partition_type\"]\n",
    "            }\n",
    "            columns = info[\"columns\"]\n",
    "            \n",
    "            # 构建字段信息\n",
    "            columns_info = \"\\n\".join([\n",
    "                f\"  - {col['name']} ({col['type']})\" + \n",
    "                (f\" - {col['comment']}\" if col.get('comment') else \"\")\n",
    "                for col in columns\n",
    "            ])\n",
    "            \n",
    "            table_info.append(f\"\"\"\n",
    "表名: {table_name}\n",
    "类型: {table_type}\n",
    "分区信息: {partition_info}\n",
    "字段列表:\n",
    "{columns_info}\n",
    "\"\"\")\n",
    "            \n",
    "        prompt = f\"\"\"请根据以下信息分析用户问题需要用到哪些表：\n",
    "\n",
    "用户问题: {question}\n",
    "\n",
    "可用的表信息:\n",
    "{\"\".join(table_info)}\n",
    "\n",
    "请列出问题中涉及到的表名，并说明选择原因。\n",
    "注意：\n",
    "1. 只返回确实需要用到的表\n",
    "2. 每个表都要说明使用原因\n",
    "3. 返回格式要求：\n",
    "[\n",
    "    {{\"table_name\": \"表名1\", \"reason\": \"使用原因1\"}},\n",
    "    {{\"table_name\": \"表名2\", \"reason\": \"使用原因2\"}}\n",
    "]\n",
    "\"\"\"\n",
    "\n",
    "        # 调用大模型分析\n",
    "        response = self.openai_client.chat.completions.create(\n",
    "            model=\"gpt-4o-mini\",\n",
    "            messages=[\n",
    "                {\"role\": \"system\", \"content\": \"你是一个专业的数据分析师，负责分析用户问题需要用到哪些表。\"},\n",
    "                {\"role\": \"user\", \"content\": prompt}\n",
    "            ],\n",
    "            temperature=0.1\n",
    "        )\n",
    "        \n",
    "        # 解析响应\n",
    "        try:\n",
    "            tables = eval(response.choices[0].message.content.strip())\n",
    "            # 获取每个表的详细信息\n",
    "            return [\n",
    "                self._get_table_partition_info(table[\"table_name\"])\n",
    "                for table in tables\n",
    "            ]\n",
    "        except Exception as e:\n",
    "            raise ValueError(f\"解析表信息失败: {str(e)}\") "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
