{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f23dd574-6704-4f9d-8a8f-5bd43d85f07a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from odps import ODPS\n",
    "import pandas as pd\n",
    "import time\n",
    "from odps.tunnel import InstanceTunnel\n",
    "from odps.errors import ODPSError\n",
    "\n",
    "project_name='your project'\n",
    "end_point='your end_point'\n",
    "access_id=os.getenv('ALIBABA_CLOUD_ACCESS_KEY_ID')\n",
    "access_key=os.getenv('ALIBABA_CLOUD_ACCESS_KEY_SECRET')\n",
    "\n",
    "# 1. 初始化 ODPS 连接\n",
    "odps = ODPS(access_id, access_key,project=project_name, endpoint=end_point)\n",
    "\n",
    "# 2. 提交 SQL 查询任务\n",
    "sql = \"\"\"\n",
    "your sql;     \n",
    "\"\"\"\n",
    "\n",
    "instance = odps.run_sql(sql)  # 提交异步任务\n",
    "print(f\"任务实例ID: {instance.id}\")\n",
    "print(f\"Logview 地址: {instance.get_logview_address()}\")  # 关键：查看执行日志\n",
    "\n",
    "# 等待任务完成（增加超时和状态检查）\n",
    "max_wait_seconds = 3600  # 最长等待 1 小时\n",
    "start_time = time.time()\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        instance.wait_for_success(interval=10)  # 每 10 秒检查一次状态\n",
    "        break\n",
    "    except ODPSError as e:\n",
    "        if \"InstanceNotTerminate\" in str(e):\n",
    "            if time.time() - start_time > max_wait_seconds:\n",
    "                raise TimeoutError(\"任务等待超时\")\n",
    "            print(\"任务仍在运行，继续等待...\")\n",
    "            time.sleep(10)\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# 确认任务成功完成（而非失败或取消）\n",
    "if instance.is_successful():\n",
    "    print(\"任务成功完成\")\n",
    "else:\n",
    "    raise RuntimeError(f\"任务失败，状态: {instance.status}, 错误信息: {instance.get_task_results().get('Error')}\")\n",
    "\n",
    "# 4. 使用 InstanceTunnel 下载结果\n",
    "tunnel = InstanceTunnel(odps)\n",
    "download_session = tunnel.create_download_session(instance.id)\n",
    "\n",
    "# 每100万写到一个文件\n",
    "csv_file = 'output_data' #输出文件名\n",
    "batchSize=10  #批次大小\n",
    "fileNum = download_session.count//batchSize\n",
    "lastNum = download_session.count%batchSize\n",
    "totalFileNum = fileNum+1 if lastNum>0 else fileNum\n",
    "header = ','.join([col.name for col in download_session.schema.columns]) + '\\n'\n",
    "for index in range(totalFileNum):  \n",
    "    startNo=0 if index==0 else index*batchSize\n",
    "    maxNo= lastNum if totalFileNum==index+1 else batchSize\n",
    "    fileName = f\"{csv_file}_{index}.csv\"\n",
    "    with open(fileName, 'wb') as f:\n",
    "        # 写入 CSV 表头\n",
    "        f.write(header.encode('utf-8'))\n",
    "        # 打开分片读取器\n",
    "        with download_session.open_record_reader(startNo, maxNo) as reader:\n",
    "            # 逐行读取记录\n",
    "            for record in reader:\n",
    "                # 将记录转换为 CSV 行（假设字段为字符串类型）\n",
    "                csv_line = \",\".join([str(val) for val in record.values]) + \"\\n\"\n",
    "                f.write(csv_line.encode('utf-8'))\n",
    "        f.close()\n",
    "        print(f\"数据已导出到: {fileName}\") \n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
